"use client"
// import Footer from "@/component/layout/footer/footer"
// import Header from "@/component/layout/header/header"

import Filter from "@/component/Layout/Filter"
import Header from "@/component/Layout/Header"
import Menu from "@/component/Layout/Menu"
import NavBarLeft from "@/component/Layout/NavBarLeft"
import NavBarOnHide from "@/component/Layout/NavBarOnHide"

import { useEffect, useState } from "react"
import { useMediaQuery } from "react-responsive"



// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
const [hideNav, setHideNav]= useState<boolean>(false)
const [changeFilter,setChangeFilter]= useState<boolean>(false)
const [changeHeader,setChangeHeader]= useState<boolean>(false)
const is1024 = useMediaQuery({ maxWidth: 1024 }); 
const is768 = useMediaQuery({ maxWidth: 768 }); 
useEffect(() => {
    setHideNav(is1024); 
  }, [is1024, setHideNav]);
  useEffect(() => {
    setChangeFilter(is1024); 
  }, [is1024, setChangeFilter]);
  useEffect(()=>{
    setChangeHeader(is768); 
  },[is768,setChangeHeader]);
  return (
    
    <html lang="en" className="mdl-js">

      <body>
      <Header 
      setHideNav={setHideNav}
      hideNav={hideNav}
      is1024={is1024}
      is768={is768}
      />
      <div className="flex ">
        <NavBarLeft 
        setHideNav={setHideNav}
        hideNav={hideNav}
        
        />
        <NavBarOnHide
        setHideNav={setHideNav}
        hideNav={hideNav}
        />
      <div className="flex flex-col w-full ">
<Filter 
setChangeFilter={setChangeFilter}
changeFilter={changeFilter}
/>
<Menu/>
{children}
       </div>
      </div>
        </body>
   
    </html>
  )
}
