
// import Footer from "@/component/layout/footer/footer"
// import Header from "@/component/layout/header/header"

import Filter from "@/component/Layout/Filter"
import Header from "@/component/Layout/Header"
import Menu from "@/component/Layout/Menu"
import NavBarLeft from "@/component/Layout/NavBarLeft"



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    
    <html lang="en" className="mdl-js">

      <body>
      <Header/>
      <div className="flex ">
        <NavBarLeft/>
      <div className="flex flex-col w-4/5 ">
<Filter/>
<Menu/>
{children}
       </div>
      </div>
        </body>
   
    </html>
  )
}
